### ISSUE TITLE
I tried your project but doesnt seem to work

### ISSUE THREAD

**Issue by nexeh** [itsfadnis/fetch-interceptor#22]
So based on your documentation i added the following to my application. as you can see i just added simple console statements to prove it was working. i get the "onBeforeRequest" and nothing else. In my case i watch to catch all 401 but based on this example thats not going to work. As a result im going to uninstall but i wanted to give you feed back before i did.

```
import FetchInterceptor from 'fetch-interceptor'

// Register interceptor hooks
const interceptor = FetchInterceptor.register({
  onBeforeRequest(request, controller) {
    // Hook before request
    console.log("onBeforeRequest")
  },
  onRequestSuccess(response, request, controller) {
    // Hook on response success
     console.log("onRequestSuccess")
  },
  onRequestFailure(response, request, controller) {
    // Hook on response failure
    console.log("onRequestFailure")
  }
});

// Make fetch requests to see interceptor in action
fetch('http://whatever.com/whatever');
```

**Comment by itsfadnis** [comment]
@nexeh Sorry to hear that.

Here's a demo I quickly tried out:
https://repl.it/repls/DeepWellwornPayware

Would be great if you could answer couple questions:
1. Are you running it on node js or the browser?
2. Is [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) & [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) available in the global environment?

For it to work:
1. Make sure [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is globally available
2. Please downgrade to `v1.0.3` if [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) is not available globally

**Comment by nexeh** [comment]
I am running it in a react application. that was a copy and paste from my app.js file. fetch is already in use and works fine. im running in Chrome. I dont know anything about AboutSignal.

**Comment by itsfadnis** [comment]
Well you can't expect it to work if you're not sure about the pre-requisites. Downgrade to version `1.0.3` to get it to work without `AbortSignal`.

**Comment by nexeh** [comment]
I apologize i miss read your original comment about AbortSignal. Im running in chrome (Version 80.0.3987.163 (Official Build) (64-bit) which according to your link: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal#Browser_compatibility it is available after version 66 so I have no issues there.

Again, I just wanted to let you know. Thanks for getting back to me.
